FROM python:3

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY src/ /app/src/
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Set the entry point
CMD ["python", "src/public_app.py"]
