  GNU nano 6.2                                        Dockerfile_local                                                  # Use an official Python runtime as a base image
FROM python:3

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY src/ /app/src/
COPY requirements_local.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/requirements_local.txt

# Set the entry point
CMD ["python", "src/local_app.py"]